version: '3.7'
services:

  mongodb_container:
    image: 
       mongo:4.2    
    container_name: 
      'mongo'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  rabbitmq:
     image: 
       rabbitmq:3-management-alpine
     container_name: 
        'rabbitmq'
     ports:
       - 5672:5672
       - 15672:15672
     volumes:
       - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
       - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  prometheus:
     image: 
        prom/prometheus
     container_name: 
        'prometheus'
     restart: 
        always
     ports:
        - 9090:9090
     volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
     networks:
          - dotnetcorepromgrafana

  grafana: 
     image: 
      grafana/grafana
     container_name: 
        'grafana'
     environment:
       - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
     restart: 
        always
     ports:
       - 3000:3000
     networks:
         - dotnetcorepromgrafana

volumes:
  mongodb_data_container:

networks:
  dotnetcorepromgrafana:
     driver: bridge



