global:
  scrape_interval:     10s 
scrape_configs:

  - job_name: 'prometheusgrafana-read-prometheus'
    static_configs:
    # replace the IP with your local IP for development
    - targets: ['192.168.1.62:7000']